Source file `/home/valenca/.emacs.d/auto-complete-config.el' newer than byte-compiled file
For information about GNU Emacs and the GNU system, type C-h C-a.
index.jsp has auto save data; consider M-x recover-this-file
Loading vc-git...done
scroll-up-command: End of buffer
Mark set
Error during redisplay: (args-out-of-range 2676 2680)
Mark saved where search started [3 times]
Saving file /home/valenca/Uni/ES/socnetes/src/Socnet.java...
Wrote /home/valenca/Uni/ES/socnetes/src/Socnet.java
Auto-saving...
(No changes need to be saved)
Mark set
scroll-down-command: Beginning of buffer
Saving file /home/valenca/Uni/ES/socnetes/src/Socnet.java...
Wrote /home/valenca/Uni/ES/socnetes/src/Socnet.java
Saving file /home/valenca/Uni/ES/socnetes/src/Socnet.java...
Wrote /home/valenca/Uni/ES/socnetes/src/Socnet.java
Mark set
Saving file /home/valenca/Uni/ES/socnetes/src/Socnet.java...
Wrote /home/valenca/Uni/ES/socnetes/src/Socnet.java
Mark set
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
Mark set [2 times]
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
Error during redisplay: (args-out-of-range 1369 1380)
byte-code: Beginning of buffer [8 times]
Mark set [4 times]
Saving file /home/valenca/Uni/ES/socnetes/index.jsp...
Wrote /home/valenca/Uni/ES/socnetes/index.jsp
Mark set
Auto-saving...done
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
(No changes need to be saved)
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
Mark set [2 times]
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
byte-code: Beginning of buffer [11 times]
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
Mark set [2 times]
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
Mark set [4 times]
Saving file /home/valenca/Uni/ES/socnetes/index.jsp...
Wrote /home/valenca/Uni/ES/socnetes/index.jsp
Mark set [3 times]
Auto-saving...done
Mark set
Saving file /home/valenca/Uni/ES/socnetes/index.jsp...
Wrote /home/valenca/Uni/ES/socnetes/index.jsp
Mark set
Saving file /home/valenca/Uni/ES/socnetes/index.jsp...
Wrote /home/valenca/Uni/ES/socnetes/index.jsp
Mark set
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
Quit
(No changes need to be saved)
Buffer HomeSv.java modified; kill anyway? (y or n)  n
Saving file /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java...
Wrote /home/valenca/Uni/ES/socnetes/src/servlets/HomeSv.java
(No changes need to be saved) [2 times]
